### ISSUE TITLE
无法处理 成绩为“优秀”或为浮点数的情况 【已解决】

### ISSUE THREAD

**Issue by wuzirui** [YaooXu/BIT_Score_Inquiry#1]
invalid literal for int() with base 10: '95.6'
invalid literal for int() with base 10: '优秀'

**Comment by YaooXu** [comment]
了解，感谢反馈bug，我今天修一下 (不过我是真不知道还有这样的分数...

**Comment by YaooXu** [comment]
> invalid literal for int() with base 10: '95.6'
> invalid literal for int() with base 10: '优秀'

请问一下，贵院计算加权的时候是怎样处理成绩为‘优秀’这种类型的课程的呢。

**Comment by wuzirui** [comment]
我咨询一下教务老师吧

**Comment by wuzirui** [comment]
按学生手册，优秀、良好、中等、合格、不合格时，分别折算为95分、85分、75分、65分、0分

**Comment by YaooXu** [comment]
> 按学生手册，优秀、良好、中等、合格、不合格时，分别折算为95分、85分、75分、65分、0分

已添加bug-fix分支，麻烦宁测试一下，测试无误后我再合并到master，十分感谢~

**Comment by wuzirui** [comment]
![image](https://user-images.githubusercontent.com/7344146/92075102-51479f80-edea-11ea-86d4-8e330b8a5f83.png)

**Comment by wuzirui** [comment]
LT-2871369-oGB0e5zhLtGgC50jUHnkCnv7qSmfTX-1599111249464 e1s1
第1次查询 状态: 200
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
2019-2020-1 专业导论 95 1.0
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'>=' not supported between instances of 'NoneType' and 'int'
'95.6'
'>=' not supported between instances of 'NoneType' and 'int'

**Comment by YaooXu** [comment]
一个变量拼错了。。。麻烦宁再试试，这下应该没问题了

**Comment by YaooXu** [comment]
> LT-2871369-oGB0e5zhLtGgC50jUHnkCnv7qSmfTX-1599111249464 e1s1
> 第1次查询 状态: 200
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> 2019-2020-1 专业导论 95 1.0
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '>=' not supported between instances of 'NoneType' and 'int'
> '95.6'
> '>=' not supported between instances of 'NoneType' and 'int'

一个变量拼错了。。。麻烦宁再试试，这下应该没问题了

**Comment by wuzirui** [comment]
好像浮点数的情况还是有一点点问题,我调一下叭

**Comment by YaooXu** [comment]
> 好像浮点数的情况还是有一点点问题,我调一下叭

宁能提供一下包含了浮点成绩和‘合格’成绩的html页面吗，只用包含了这俩就行，我这边因为没有这俩不太好测试。

就是把那个查成绩的页面ctrl s保存下来发给我邮箱就行

**Comment by wuzirui** [comment]
--
  | <tr >
  | <td style="">21</td>
  | <td style="">2019-2020-2</td>
  | <td style="" align="left">100980003</td>
  | <td style="" align="left">军事理论</td>
  |  
  | <td style=" "><a style="" href="javascript:this.top.vpn_inject_scripts_window(this);vpn_eval((function () { JsMod(&#39;/jsxsd/kscj/pscj_list.do?xs0101id=1120190773&amp;jx0404id=201920202002585&amp;zcj=95.6&#39;,700,500) }).toString().slice(14, -2))">95.6</a></td>
  |  
  |  
  | <td style=""></td>
  | <td style="">2</td>
  | <td style="">36</td>
  | <td style="">正常考试</td>
  | <td style="">考查</td>
  | <td style="">必修</td>
  | <td style="">公共基础课程</td>
  | <td style=""></td>
  | <td style=""></td>
  | <td style="">是</td>
  | <td>
  |  
  | <a href="javascript:this.top.vpn_inject_scripts_window(this);vpn_eval((function () { void(0); }).toString().slice(14, -2))" onclick="var vpn_return;eval(vpn_rewrite_js((function () { JsMod(&#39;/jsxsd/kscj/cjfx?xs0101id=1120190773&amp;jx0404id=201920202002585&amp;kch=100980003&amp;zcj=95.6&amp;isfirst=1&amp;cjfs=D&#39;,700,500) }).toString().slice(14, -2), 2));return vpn_return;">成绩分析</a>
  |  
  | </td>
  | </tr>
  |

**Comment by wuzirui** [comment]
| <td style="" align="left">军事理论</td>
  |  
  | <td style=" "><a style="" href="javascript:this.top.vpn_inject_scripts_window(this);vpn_eval((function () { JsMod(&#39;/jsxsd/kscj/pscj_list.do?xs0101id=1120190773&amp;jx0404id=201920202002585&amp;zcj=95.6&#39;,700,500) }).toString().slice(14, -2))">95.6</a></td>

好像github会自动解释html代码?

**Comment by wuzirui** [comment]
'@' 代替 '>'

--
  | <tr >
  | <td style="">21</td>
  | <td style="">2019-2020-2</td>
  | <td style="" align="left">100980003</td>
  | <td style="" align="left">军事理论</td>
  |  
  | <td style=" "@<a style="" href="javascript:this.top.vpn_inject_scripts_window(this);vpn_eval((function () { JsMod(&#39;/jsxsd/kscj/pscj_list.do?xs0101id=1120111111&amp;jx0404id=201920202002585&amp;zcj=95.6&#39;,700,500) }).toString().slice(14, -2))"@95.6</a@</td@
  |  
  |  
  | <td style=""></td>
  | <td style="">2</td>
  | <td style="">36</td>
  | <td style="">正常考试</td>
  | <td style="">考查</td>
  | <td style="">必修</td>
  | <td style="">公共基础课程</td>
  | <td style=""></td>
  | <td style=""></td>
  | <td style="">是</td>
  | <td>
  |  
  | <a href="javascript:this.top.vpn_inject_scripts_window(this);vpn_eval((function () { void(0); }).toString().slice(14, -2))" onclick="var vpn_return;eval(vpn_rewrite_js((function () { JsMod(&#39;/jsxsd/kscj/cjfx?xs0101id=1120111111&amp;jx0404id=201920202002585&amp;kch=100980003&amp;zcj=95.6&amp;isfirst=1&amp;cjfs=D&#39;,700,500) }).toString().slice(14, -2), 2));return vpn_return;"@成绩分析</a@
  |  
  | </td>
  | </tr>
  |

**Comment by YaooXu** [comment]
我知道问题了 python的isdigit遇到浮点会返回false，我的问题 (捂脸

**Comment by YaooXu** [comment]
> 好像浮点数的情况还是有一点点问题,我调一下叭

这下真的可以了，我本地也测过了 (捂脸

**Comment by wuzirui** [comment]
ok 了
